[grpc]
  address = ["unix:///run/buildkit/buildkitd.sock", "tcp://0.0.0.0:9999"]
  uid = 0
  gid = 0

[worker.oci]
  enabled = false

[worker.containerd]
  enabled = true
  gc = true

[worker.containerd.runtime]
  name = "io.containerd.runc.v2"
  path = "/path/to/containerd/runc/shim"
  options = { BinaryName = "runc" }

[[worker.containerd.gcpolicy]]
  filters = ["type==source.local", "type==exec.cachemount", "type==source.git.checkout"]
  reservedSpace = "10GiB"
[[worker.containerd.gcpolicy]]
  all = true
  reservedSpace = "50GiB"
