---
name: Talos Boot Assets Generation

on:
  workflow_dispatch:
    inputs:
      talos_release_tag:
        description: Talos release tag
        required: true
      build_pkgs:
        description: Build pkgs (kernel, drivers)
        type: boolean
        default: true
        required: false
      build_extensions:
        description: Build extensions
        type: boolean
        default: true
        required: false
      build_talos:
        description: Build talos
        type: boolean
        default: true
        required: false

concurrency:
  group: ${{ github.actor }}-build

env:
  AMD_UCODE_VERSION: "20240811"
  GLIBC_VERSION: "2.40"
  ISCSI_TOOLS_VERSION: "v0.1.5"
  NVIDIA_CONTAINER_TOOLKIT_VERSION: "v1.16.1"
  NVIDIA_DRIVER_VERSION: "550.90.07"
  UTIL_LINUX_TOOLS_VERSION: "2.40.2"
  ZFS_VERSION: "2.2.6"

jobs:
  set-rel:
    name: Set release branch
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Talos release version
        id: set
        run: |
          release_branch=release-$(grep -Eo '[0-9]\.[0-9]+' <<< ${{ inputs.talos_release_tag }})
          echo "release_branch=$release_branch" >> $GITHUB_OUTPUT

    outputs:
      release_branch: ${{ steps.set.outputs.release_branch }}

  build-pkgs:
    needs: [set-rel]
    if: ${{ !failure() && inputs.build_pkgs }}
    name: Build packages
    runs-on: [runs-on,runner=32cpu-linux-x64,hdd=80,"run-id=${{ github.run_id }}"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: jfroy/siderolabs-pkgs
          ref: ${{ needs.set-rel.outputs.release_branch }}-jfroy
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-config-inline: |
            [worker.oci]
              gc = true
              gckeepstorage = 50000

              [[worker.oci.gcpolicy]]
                keepBytes = 10737418240
                keepDuration = 604800
                filters = [ "type==source.local", "type==exec.cachemount", "type==source.git.checkout"]
              [[worker.oci.gcpolicy]]
                all = true
                keepBytes = 53687091200

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: |
          make ca-certificates base kernel nvidia-open-gpu-kernel-modules-production-pkg zfs-pkg \
            PLATFORM=linux/amd64 \
            USERNAME="${{ github.actor }}/talos" \
            TAG="${{ inputs.talos_release_tag }}" \
            PUSH="true"

  build-extensions:
    needs: [set-rel, build-pkgs]
    if: ${{ !failure() && inputs.build_extensions }}
    name: Build extensions
    runs-on: [runs-on,runner=32cpu-linux-x64,hdd=80,"run-id=${{ github.run_id }}"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: jfroy/siderolabs-extensions
          ref: ${{ needs.set-rel.outputs.release_branch }}-jfroy
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: |
          make glibc nvidia-container-toolkit nvidia-open-gpu-kernel-modules-production zfs \
            PLATFORM=linux/amd64 \
            PKGS="${{ inputs.talos_release_tag }}" \
            PKGS_PREFIX="ghcr.io/${{ github.actor }}/talos" \
            USERNAME="${{ github.actor }}/talos" \
            TAG="${{ inputs.talos_release_tag }}" \
            PUSH="true"

  build-talos:
    needs: [set-rel, build-pkgs, build-extensions]
    if: ${{ !failure() && inputs.build_talos }}
    name: Build talos
    runs-on: [runs-on,runner=32cpu-linux-x64,hdd=80,"run-id=${{ github.run_id }}"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: jfroy/siderolabs-talos
          ref: ${{ needs.set-rel.outputs.release_branch }}-jfroy
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: |
          make imager installer talosctl-image \
            INSTALLER_ARCH="amd64" \
            PLATFORM="linux/amd64" \
            PKG_KERNEL="ghcr.io/${{ github.actor }}/talos/kernel:${{ inputs.talos_release_tag }}" \
            USERNAME="${{ github.actor }}/talos" \
            TAG="${{ inputs.talos_release_tag }}" \
            PUSH="true"

  build-release:
    needs: [set-rel, build-talos]
    if: ${{ !failure() }}
    name: Build release
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Build
        env:
          PCR_SIGNING_KEY: ${{ secrets.PCR_SIGNING_KEY }}
          UKI_SIGNING_CERT: ${{ secrets.UKI_SIGNING_CERT }}
          UKI_SIGNING_KEY: ${{ secrets.UKI_SIGNING_KEY }}
        run: |
          mkdir _out
          echo "${PCR_SIGNING_KEY}" > ./_out/pcr-signing-key.pem
          echo "${UKI_SIGNING_CERT}" > ./_out/uki-signing-cert.pem
          echo "${UKI_SIGNING_KEY}" > ./_out/uki-signing-key.pem
          docker run --rm -v ./_out:/_out \
            ghcr.io/${{ github.actor }}/talos/talosctl:${{ inputs.talos_release_tag }} \
              gen secureboot database --include-microsoft-certs
          mv _out secureboot
          mkdir _out
          docker run --rm -v ./secureboot:/secureboot:ro -v ./_out:/out \
            ghcr.io/${{ github.actor }}/talos/imager:${{ inputs.talos_release_tag }} \
              secureboot-installer \
              --arch amd64 \
              --base-installer-image ghcr.io/${{ github.actor }}/talos/installer:${{ inputs.talos_release_tag }} \
              --system-extension-image ghcr.io/jfroy/talos/glibc:${{ env.GLIBC_VERSION }} \
              --system-extension-image ghcr.io/jfroy/talos/zfs:${{ env.ZFS_VERSION }}-${{ inputs.talos_release_tag }} \
              --system-extension-image ghcr.io/siderolabs/amd-ucode:${{ env.AMD_UCODE_VERSION }} \
              --system-extension-image ghcr.io/siderolabs/iscsi-tools:${{ env.ISCSI_TOOLS_VERSION }} \
              --system-extension-image ghcr.io/siderolabs/util-linux-tools:${{ env.UTIL_LINUX_TOOLS_VERSION }} \
              --extra-kernel-arg amd_pstate=active \
              --extra-kernel-arg console=tty0 \
              --extra-kernel-arg console=ttyS0 \
              --extra-kernel-arg talos.network.interface.ignore=eth0 \
              --extra-kernel-arg talos.network.interface.ignore=enp66s0f0 \
              --extra-kernel-arg talos.network.interface.ignore=eth1 \
              --extra-kernel-arg talos.network.interface.ignore=enp66s0f1
          docker run --rm --privileged -v ./secureboot:/secureboot:ro -v ./_out:/out -v /dev:/dev \
            ghcr.io/${{ github.actor }}/talos/imager:${{ inputs.talos_release_tag }} \
              secureboot-iso \
              --arch amd64 \
              --base-installer-image ghcr.io/${{ github.actor }}/talos/installer:${{ inputs.talos_release_tag }} \
              --system-extension-image ghcr.io/siderolabs/amd-ucode:${{ env.AMD_UCODE_VERSION }} \
              --system-extension-image ghcr.io/siderolabs/util-linux-tools:${{ env.UTIL_LINUX_TOOLS_VERSION }} \
              --extra-kernel-arg console=tty0 \
              --extra-kernel-arg console=ttyS0 \
              --extra-kernel-arg net.ifnames=0 \
              --extra-kernel-arg talos.network.interface.ignore=eth0 \
              --extra-kernel-arg talos.network.interface.ignore=eth1 \
              --extra-kernel-arg bond=bond0:eth2,eth3:mode=802.3ad:1500 \
              --extra-kernel-arg ip=bond0:dhcp

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: imjasonh/setup-crane@v0.4
      - name: Push installer image
        run: |
          crane push \
            --platform linux/amd64 \
            _out/installer-amd64-secureboot.tar \
            ghcr.io/${{ github.actor }}/talos/secureboot-installer:${{ inputs.talos_release_tag }}

      - name: Fetch Talos release body
        id: talos-release-body
        run: |
          echo 'talos_release_body<<EOF' >> $GITHUB_OUTPUT
          curl -sL https://api.github.com/repos/siderolabs/talos/releases/tags/${{ inputs.talos_release_tag }} | jq -r ".body" >> $GITHUB_OUTPUT
          echo EOF >> $GITHUB_OUTPUT

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.talos_release_tag }}
          body: ${{ steps.talos-release-body.outputs.talos_release_body }}
          files: _out/metal-amd64-secureboot.iso
