---
name: Talos Boot Assets Generation

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: Container image tag for the release
        required: true
      siderolabs_tag:
        description: Upstream release tag for extensions manifest
        required: true
      build_pkgs:
        description: Build pkgs
        type: boolean
        default: true
        required: false
      build_extensions:
        description: Build extensions
        type: boolean
        default: true
        required: false
      build_talos:
        description: Build talos
        type: boolean
        default: true
        required: false
      build_nvidia_driver_container:
        description: Build NVIDIA driver container
        type: boolean
        default: false
        required: false

concurrency:
  group: ${{ github.actor }}-build

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write
      packages: write

    steps:
      - name: Install cosign
        uses: sigstore/cosign-installer@v3

      - name: Install crane
        uses: imjasonh/setup-crane@v0.4

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3

      - name: Set release branch
        id: set-rel
        run: |
          release_branch=release-$(grep -Eo '[0-9]\.[0-9]+' <<< ${{ inputs.release_tag }})
          echo "release_branch=$release_branch" >> $GITHUB_OUTPUT

      - name: Login ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:gha-talos-boot-assets
          version: 1.78.0

      - name: Generate tailscale keys
        id: ts-keys
        run: |
          ts_access_token=$(curl --silent \
            -d "client_id=${{ secrets.TS_OAUTH_CLIENT_ID }}" \
            -d "client_secret=${{ secrets.TS_OAUTH_SECRET }}" \
            "https://api.tailscale.com/api/v2/oauth/token" | jq -r '.access_token')
          if [ "$ts_access_token" = "null" ]; then
            echo "Tailscale API returned null access token"
            exit 1
          fi
          echo "::add-mask::$ts_access_token"

          ts_auth_key=$(curl --silent --request POST \
            --url 'https://api.tailscale.com/api/v2/tailnet/-/keys?all=true' \
            --header "Authorization: Bearer $ts_access_token" \
            --header 'Content-Type: application/json' \
            --data '{
            "capabilities": {
              "devices": {
                "create": {
                  "reusable": false,
                  "ephemeral": true,
                  "preauthorized": true,
                  "tags": ["tag:gha-talos-boot-assets"]
                }
              }
            },
            "expirySeconds": 300
          }' | jq -r '.key')
          if [ "$ts_auth_key" = "null" ]; then
            echo "Tailscale API returned null auth key"
            exit 1
          fi
          echo "::add-mask::$ts_auth_key"
          echo "ts_auth_key=$ts_auth_key" >> $GITHUB_OUTPUT

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::992382661722:role/talos-boot-assets-gha-terraform-buildkit
          aws-region: us-west-2

      - name: Checkout workflow
        uses: actions/checkout@v4

      - name: Terraform apply
        id: terraform-apply
        run: |
          terraform init
          terraform apply -auto-approve \
            -var "ts_auth_key=${{ steps.ts-keys.outputs.ts_auth_key }}"
          instance_amd64_id=$(terraform output --raw instance_amd64_id)
          instance_arm64_id=$(terraform output --raw instance_arm64_id)
          attempt=0
          while ! tailscale ip $instance_amd64_id; do
              attempt=$((attempt + 1))
              if [ $attempt -gt 5 ]; then
                  exit 1
              fi
              sleep 5
          done
          attempt=0
          while ! tailscale ip $instance_arm64_id; do
              attempt=$((attempt + 1))
              if [ $attempt -gt 5 ]; then
                  exit 1
              fi
              sleep 5
          done
          echo "instance_amd64_id=$instance_amd64_id" >> $GITHUB_OUTPUT
          echo "instance_arm64_id=$instance_arm64_id" >> $GITHUB_OUTPUT

      - name: Setup buildkit
        uses: docker/setup-buildx-action@v3
        with:
          driver: remote
          endpoint: tcp://${{ steps.terraform-apply.outputs.instance_amd64_id }}:9999
          platforms: linux/amd64
          append: |
            - endpoint: tcp://${{ steps.terraform-apply.outputs.instance_arm64_id }}:9999
              platforms: linux/arm64

      - name: Checkout pkgs
        if: ${{ !failure() && !cancelled() && inputs.build_pkgs }}
        uses: actions/checkout@v4
        with:
          path: pkgs
          repository: jfroy/siderolabs-pkgs
          ref: ${{ steps.set-rel.outputs.release_branch }}-jfroy
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build pkgs
        id: build-pkgs
        if: ${{ !failure() && !cancelled() && inputs.build_pkgs }}
        working-directory: ./pkgs
        run: |
          mkdir -p _out
          for target in ca-certificates base kernel nvidia-open-gpu-kernel-modules-production-pkg zfs-pkg; do
            make $target \
              PLATFORM="linux/amd64,linux/arm64" \
              USERNAME="${{ github.actor }}" \
              REGISTRY_AND_USERNAME="ghcr.io/${{ github.actor }}/siderolabs" \
              TAG="${{ inputs.release_tag }}" \
              PUSH="true" \
              CI_ARGS="--metadata-file _out/meta --build-arg=BUILDKIT_MULTI_PLATFORM=1"
            cat _out/meta
            cosign sign --yes --recursive "$(jq -j .\"image.name\" _out/meta)@$(jq -j .\"containerimage.digest\" _out/meta)"
          done

      - name: Checkout extensions
        if: ${{ !failure() && !cancelled() && (inputs.build_extensions || steps.build-pkgs.conclusion == 'success') }}
        uses: actions/checkout@v4
        with:
          path: extensions
          repository: jfroy/siderolabs-extensions
          ref: ${{ steps.set-rel.outputs.release_branch }}-jfroy
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build extensions
        if: ${{ !failure() && !cancelled() && (inputs.build_extensions || steps.build-pkgs.conclusion == 'success') }}
        working-directory: ./extensions
        run: |
          make _out/bldr
          crane export ghcr.io/siderolabs/extensions:${{ inputs.siderolabs_tag }} | tar x -C internal/extensions/
          for target in glibc nvidia-driver-production zfs; do
            make $target \
              PLATFORM="linux/amd64,linux/arm64" \
              PKGS="${{ inputs.release_tag }}" \
              PKGS_PREFIX="ghcr.io/${{ github.actor }}/siderolabs" \
              REGISTRY="ghcr.io/${{ github.actor }}" \
              TAG="${{ inputs.release_tag }}" \
              PUSH="true" \
              CI_ARGS="--metadata-file _out/meta --build-arg=BUILDKIT_MULTI_PLATFORM=1"
            image="$(jq -j .\"image.name\" _out/meta)@$(jq -j .\"containerimage.digest\" _out/meta)"
            cosign sign --yes --recursive "$image"
            echo "$image" >> internal/extensions/image-digests
            crane export "$image" - | tar x -O --occurrence=1 manifest.yaml | yq -r ". += {\"$image\": {\"author\": .metadata.author, \"description\": .metadata.description}} | del(.metadata, .version)" - >> internal/extensions/descriptions.yaml
          done

      - name: Build extensions manifest
        if: ${{ !failure() && !cancelled() && (inputs.build_extensions || steps.build-pkgs.conclusion == 'success') }}
        working-directory: ./extensions
        run: |
          mkdir -p _out
          make docker-extensions \
            PLATFORM="linux/amd64,linux/arm64" \
            PKGS="${{ inputs.release_tag }}" \
            PKGS_PREFIX="ghcr.io/${{ github.actor }}/siderolabs" \
            REGISTRY="ghcr.io/${{ github.actor }}" \
            TAG="${{ inputs.release_tag }}" \
            TARGET_ARGS="--tag=ghcr.io/${{ github.actor }}/siderolabs/extensions:${{ inputs.release_tag }} --push=true" \
            CI_ARGS="--metadata-file _out/meta --build-arg=BUILDKIT_MULTI_PLATFORM=1"
          cosign sign --yes --recursive "$(jq -j .\"image.name\" _out/meta)@$(jq -j .\"containerimage.digest\" _out/meta)"

      - name: Checkout talos
        if: ${{ !failure() && !cancelled() && (inputs.build_talos || steps.build-pkgs.conclusion == 'success') }}
        uses: actions/checkout@v4
        with:
          path: talos
          repository: jfroy/siderolabs-talos
          ref: ${{ steps.set-rel.outputs.release_branch }}-jfroy
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build talos
        if: ${{ !failure() && !cancelled() && (inputs.build_talos || steps.build-pkgs.conclusion == 'success') }}
        working-directory: ./talos
        run: |
          mkdir -p _out
          for target in imager installer; do
            make $target \
              PLATFORM="linux/amd64,linux/arm64" \
              PKG_KERNEL="ghcr.io/${{ github.actor }}/siderolabs/kernel:${{ inputs.release_tag }}" \
              USERNAME="${{ github.actor }}" \
              REGISTRY_AND_USERNAME="ghcr.io/${{ github.actor }}/siderolabs" \
              TAG="${{ inputs.release_tag }}" \
              PUSH="true" \
              CI_ARGS="--metadata-file _out/meta --build-arg=BUILDKIT_MULTI_PLATFORM=1"
            cosign sign --yes --recursive "$(jq -j .\"image.name\" _out/meta)@$(jq -j .\"containerimage.digest\" _out/meta)"
          done

      - name: Build talosctl
        if: ${{ !failure() && !cancelled() && (inputs.build_talos || steps.build-pkgs.conclusion == 'success') }}
        working-directory: ./talos
        run: |
          mkdir -p _out
          make talosctl-image \
            PLATFORM="linux/amd64,linux/arm64" \
            USERNAME="${{ github.actor }}" \
            REGISTRY_AND_USERNAME="ghcr.io/${{ github.actor }}/siderolabs" \
            TAG="${{ inputs.release_tag }}" \
            PUSH="true" \
            CI_ARGS="--metadata-file _out/meta --build-arg=BUILDKIT_MULTI_PLATFORM=1"
          cosign sign --yes --recursive "$(jq -j .\"image.name\" _out/meta)@$(jq -j .\"containerimage.digest\" _out/meta)"

      - name: Terraform destroy
        if: ${{ always() }}
        run: |
          terraform destroy -auto-approve \
            -var "ts_auth_key=${{ steps.ts-keys.outputs.ts_auth_key }}"
